GET http://localhost:3000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJTaGFua2FyYSIsImZ1bGxuYW1lIjoiTXVoYW1tYWQgTGF6dWFyZGkgVGltdXIiLCJlbWFpbCI6ImxhenVhcmRpdDIxQGdtYWlsLmNvbSIsInVzZXJMZXZlbCI6IlVzZXIiLCJpYXQiOjE2NzY4NjM1NjQsImV4cCI6MTY3Njk0OTk2NH0.gOcfjY_jJ04IiPJ0QcDIad8fQcysGRZ5QtZ4XLUR9kg

###
POST  http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "lazuardit21@gmail.com",
    "password" : "123456"
}